version: "3.7"

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"

  crawler:
    build: .
    image: crawler-template
    container_name: crawler
    env_file: .env
    volumes:
      - .:/home/app
    command: pipenv run start
    depends_on:
      - selenium
